title: "My Study Blog"
description: "Notes, ideas, and learning resources"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

minimal_mistakes_skin: "default"

collections:
  posts:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "main"

author:
  name: Your Name
  bio: "Student of many things."
